// Educational scenarios checked against current official Topaz docs, 2026-10-08.
// Availability is feature-specific: always check the selected network's live UI.
export const TOPAZ_DOCS_CHECKED_AT = "2026-10-08";
export const TOPAZ_FEATURE_MISSIONS = [
  {
    title: "SHARE ENGINE", feature: "xTOPAZ BACKING & LOCAL VOTING", action: "SHARE CHECKS",
    mechanic: "Separate liquid shares, local voting stakes and permanently locked backing.",
    lesson: "xTOPAZ is a share in permanent BNB backing. Stake and vote locally to earn a spoke's voter rewards.",
    fact: "Liquid xTOPAZ does not vote or earn local voter fees by itself. Backing growth changes TOPAZ per share, not the share balance. BNB redemption returns a new permanent veTOPAZ NFT, not liquid TOPAZ.",
    factUrl: "https://www.topazdex.com/docs/xtopaz",
    goal: "Complete six checks on xTOPAZ shares, staking, wrapping and redemption.",
    hint: "READ THE POSITION · SEPARATE SHARES, VOTES AND BACKING",
    accept: "The actual asset or position and its withdrawal rules",
    avoid: "Treating liquid shares as votes, cash, or an LP position",
    recap: "xTOPAZ shares track permanent BNB backing. Local stakes vote on their own chain; wrapping burns the original NFT, and redemption returns a new permanent lock.",
    badge: "share-engineer", gradeTitle: "SHARE ENGINEER",
    choices: ["LIQUID SHARES", "LOCAL VOTING", "PERMANENT BACKING"],
    scenarios: [
      { prompt: "xTOPAZ IN YOUR WALLET", detail: "You can transfer or bridge these shares. Holding them alone does not cast votes or earn local voter fees.", correct: "LIQUID SHARES" },
      { prompt: "STAKE AND VOTE ON ARC", detail: "This position allocates to Arc gauges and claims Arc pool fees and incentives. It is not an LP NFT.", correct: "LOCAL VOTING" },
      { prompt: "TOPAZ PER SHARE INCREASES", detail: "Settled BNB backing grows without increasing your liquid share count. The backing rate is not a guaranteed dollar price.", correct: "PERMANENT BACKING" },
      { prompt: "REDEEM ON BNB", detail: "When permitted, redemption gives a new permanent veTOPAZ NFT, not liquid TOPAZ or a stablecoin.", correct: "PERMANENT BACKING" },
      { prompt: "WRAP AN ELIGIBLE veTOPAZ NFT", detail: "The original NFT is burned into the aggregate permanent lock. Its individual BNB vote allocation ends; resolve its rewards first.", correct: "PERMANENT BACKING" },
      { prompt: "ADD TO AN EXISTING SPOKE STAKE", detail: "Adding funds can relock the entire balance. Review its withdrawal date and voting restrictions before signing.", correct: "LOCAL VOTING" },
    ],
  },
  {
    title: "AUTO PILOT", feature: "TOPAZ AUTO · MANAGED RANGES", action: "AUTO DECISIONS",
    mechanic: "Manage a simulated vault's range, separate rewards and review automation risks.",
    lesson: "Topaz Auto manages a concentrated range. It passes gauge emissions through separately instead of compounding them.",
    fact: "Auto vaults hold ERC-20 shares in a managed pool position. The keeper waits for calm conditions before re-ranging. Emissions are separate claims; Auto is not the auto-compounding Topaz Vaults product. Check the live vault listing for network availability.",
    factUrl: "https://www.topazdex.com/docs/auto",
    goal: "Make six decisions about range management, claims, pauses and risk.",
    hint: "MANAGE THE RANGE · KEEP REWARDS SEPARATE · REVIEW RISK",
    accept: "Managed ranges, separate emission claims and fresh deposit reviews",
    avoid: "Assuming auto-compounding, constant in-range status or guaranteed profit",
    recap: "Auto manages range, not reward compounding. Out-of-range emissions stop; rebalancing has costs. Claims do not increase principal, and strategy deposit pauses do not require claiming before withdrawal.",
    badge: "auto-pilot", gradeTitle: "AUTO PILOT",
    choices: ["WAIT FOR CALM", "SEPARATE CLAIM", "REVIEW RISK"],
    scenarios: [
      { prompt: "OUT OF RANGE · FAST PRICE MOVE", detail: "The keeper waits for the pool price to agree with its recent time-weighted price before re-ranging. Emissions stop while out of range.", correct: "WAIT FOR CALM" },
      { prompt: "GAUGE EMISSIONS ACCRUE", detail: "TOPAZ on BNB or xTOPAZ on a supported spoke becomes claimable separately. Rewards are not sold or added to principal.", correct: "SEPARATE CLAIM" },
      { prompt: "CLAIM YOUR AUTO REWARDS", detail: "Claiming leaves vault shares and principal unchanged. This is not Topaz Vaults auto-compounding.", correct: "SEPARATE CLAIM" },
      { prompt: "THE VAULT PAUSES NEW DEPOSITS", detail: "Read the reason. Strategy pauses do not close withdrawals or reward claims, and withdrawing does not require claiming first.", correct: "REVIEW RISK" },
      { prompt: "AUTO APR LOOKS ATTRACTIVE", detail: "It estimates gauge rewards after the reward fee, excluding trading fees and compounding. Prices, impermanent loss and rebalance costs still matter.", correct: "REVIEW RISK" },
      { prompt: "PREVIEW PRICE CHANGED", detail: "Fresh reads rebuild the deposit plan. Material changes require a new review; automation does not replace transaction checks.", correct: "REVIEW RISK" },
    ],
  },
  {
    title: "ZAP LAB", feature: "SINGLE-TOKEN LIQUIDITY", action: "ZAP CHECKS",
    mechanic: "Choose the correct zap output, review a changed quote and separate staking.",
    lesson: "A CL zap splits one funding token into a new concentrated position. Its NFT starts unstaked; staking is separate.",
    fact: "CL Zap creates a new NFT in an existing initialized pool; it does not bridge assets or increase an existing NFT. Auto zaps create vault shares instead. Arc funding is ERC-20 only, with USDC reserved for gas. Check route availability and fresh minimums.",
    factUrl: "https://www.topazdex.com/docs/liquidity/zaps",
    goal: "Identify six zap outputs and the checks needed before signing.",
    hint: "IDENTIFY THE OUTPUT · REVIEW MINIMUMS · STAKE SEPARATELY",
    accept: "A new CL NFT, Auto shares, and reviewed token/range changes",
    avoid: "Assuming every zap makes xTOPAZ, bridges assets or starts emissions",
    recap: "A CL zap creates an unstaked NFT; Auto's zap creates vault shares. Review the split, range, minimum liquidity and leftovers. A changed funding token, amount or range invalidates the old review.",
    badge: "zap-specialist", gradeTitle: "ZAP SPECIALIST",
    choices: ["NEW CL NFT", "AUTO SHARES", "REVIEW AGAIN"],
    scenarios: [
      { prompt: "CUSTOM-RANGE CL ZAP", detail: "One funding token is split and deposited into a new concentrated position in an existing initialized pool. The NFT starts unstaked.", correct: "NEW CL NFT" },
      { prompt: "AUTO VAULT'S ONE-TOKEN ZAP", detail: "The deposit joins the managed vault rather than giving you a personal range NFT or xTOPAZ backing shares.", correct: "AUTO SHARES" },
      { prompt: "YOU CHANGE THE PRICE RANGE", detail: "The earlier split and minimums no longer apply. Refresh the quote and review the new bounds before signing.", correct: "REVIEW AGAIN" },
      { prompt: "ZAP FINISHES SUCCESSFULLY", detail: "The receipt identifies an unstaked position. Open it and review gauge staking separately if you want emissions.", correct: "NEW CL NFT" },
      { prompt: "NATIVE INPUT REQUESTED ON ARC", detail: "Arc has no wrapped-native zap leg. Choose supported ERC-20 funding and leave USDC for gas.", correct: "REVIEW AGAIN" },
      { prompt: "INCREASE AN EXISTING NFT", detail: "This CL Zap flow creates a new NFT; it does not increase an old one or initialize a pool. Choose the appropriate position-management flow.", correct: "REVIEW AGAIN" },
    ],
  },
  {
    title: "ROUTE CONTROL", feature: "AGGREGATION & CROSS-CHAIN DELIVERY", action: "ROUTE CHECKS",
    mechanic: "Separate winning swap routes, voting-share bridges and destination delivery.",
    lesson: "A winning quote can use Topaz, 0x or Relay. Source confirmation is not proof of destination delivery.",
    fact: "Topaz routes compete with supported aggregators. Arc cross-chain swaps use Relay. xTOPAZ moves through its separate LayerZero bridge; private swaps are another service. Review chain, approvals, fees, slippage and the destination order status.",
    factUrl: "https://www.topazdex.com/docs/trading/swaps",
    goal: "Complete six route, provider, approval and delivery checks.",
    hint: "CHECK THE WINNER · TRACK DELIVERY · SEPARATE BRIDGE JOURNEYS",
    accept: "The reviewed provider and confirmed destination receipt or order outcome",
    avoid: "Treating an approval or source receipt as a completed cross-chain swap",
    recap: "Topaz, 0x and Relay have distinct execution and approval paths. Cross-chain swaps, xTOPAZ bridging and private swaps are different journeys. Track destination delivery rather than stopping at the source receipt.",
    badge: "route-controller", gradeTitle: "ROUTE CONTROLLER",
    choices: ["REVIEW ROUTE", "TRACK DELIVERY", "xTOPAZ BRIDGE"],
    scenarios: [
      { prompt: "0x OR RELAY WINS THE QUOTE", detail: "A winning route can use other venues. Review that route's execution contract, approval scope and complete costs rather than assuming every hop is a Topaz pool.", correct: "REVIEW ROUTE" },
      { prompt: "SOURCE TRANSACTION CONFIRMED", detail: "The cross-chain destination fill is not yet proven. Follow the stored order ID for delivery or refund status.", correct: "TRACK DELIVERY" },
      { prompt: "MOVE xTOPAZ VOTING SHARES", detail: "Use the separate LayerZero xTOPAZ bridge, not an ordinary asset swap. Check its supported path and destination receipt.", correct: "xTOPAZ BRIDGE" },
      { prompt: "CROSS-CHAIN SWAP TO OR FROM ARC", detail: "The documented swap provider is Relay. Review ERC-20 USDC handling, gas and quoted destination amounts.", correct: "REVIEW ROUTE" },
      { prompt: "EXACT OUTPUT MAXIMUM INCREASES", detail: "Same-chain Topaz supports an output target bounded by maximum input. A refreshed maximum above the reviewed amount requires a fresh review.", correct: "REVIEW ROUTE" },
      { prompt: "A BROAD PERMIT IS REQUESTED", detail: "Topaz's Permit2 authorization differs from exact-amount 0x or Relay approval paths. Check the spender, amount and expiry; approval alone is not swap completion.", correct: "REVIEW ROUTE" },
    ],
  },
  {
    title: "FEE SIGNALS", feature: "DYNAMIC FEES & REWARD SEPARATION", action: "FEE CHECKS",
    mechanic: "Read the actual fee configuration and separate LP income from voter rewards.",
    lesson: "Fee settings are pool-specific. The same unit of LP liquidity earns fees or gauge emissions, not both full streams.",
    fact: "Opted-in Slipstream pools can add a capped dynamic fee based on spot/TWAP divergence. Unstaked CL liquidity may pay a surcharge when an alive gauge exists. TOPAZ rewards BNB gauge LPs; xTOPAZ rewards spoke gauge LPs. Voters claim local fees and incentives.",
    factUrl: "https://www.topazdex.com/docs/liquidity/fees",
    goal: "Classify six fee, emissions and voter-reward signals correctly.",
    hint: "READ THE POOL RULES · DO NOT ADD INCOMPATIBLE APRS",
    accept: "Pool-specific fees and the income stream for the actual position",
    avoid: "Assuming fixed fees everywhere or adding full Fee APR and Emissions APR",
    recap: "Dynamic fees require pool configuration. A fee surcharge is not a tax on the whole deposit. LP fees, LP emissions and voter fees/incentives describe different cash flows; compare each against costs and risk.",
    badge: "fee-analyst", gradeTitle: "FEE ANALYST",
    choices: ["POOL FEE RULES", "LP EMISSIONS", "VOTER REWARDS"],
    scenarios: [
      { prompt: "SPOT MOVES AWAY FROM TWAP", detail: "TWAP is the time-weighted average price. An opted-in Slipstream pool can add a dynamic fee, subject to its configured cap; not every pool enables it.", correct: "POOL FEE RULES" },
      { prompt: "UNSTAKED CL · ALIVE GAUGE", detail: "A configured share of swap fees can go to voters. This surcharge is on fees, not the entire deposit, and does not apply without an alive gauge.", correct: "POOL FEE RULES" },
      { prompt: "STAKED LP ON BNB", detail: "The staked portion earns TOPAZ gauge emissions instead of ongoing swap fees. V2 can have separate staked and unstaked balances.", correct: "LP EMISSIONS" },
      { prompt: "STAKED LP ON A SPOKE", detail: "On Robinhood Chain, Base, Ethereum or Arc, the local gauge emission token is xTOPAZ. A CL position must be in range.", correct: "LP EMISSIONS" },
      { prompt: "LOCAL GAUGE VOTER", detail: "A BNB veTOPAZ voter or a spoke xTOPAZ voting stake claims local pool fees and posted incentives, not the LP's emission stream.", correct: "VOTER REWARDS" },
      { prompt: "FULL FEE APR + EMISSIONS APR", detail: "The same unit of liquidity does not receive both full streams simultaneously. Review its actual staking state and the pool's current fee settings.", correct: "POOL FEE RULES" },
    ],
  },
] as const;

export const featureMission = (index: number): (typeof TOPAZ_FEATURE_MISSIONS)[number] | undefined => TOPAZ_FEATURE_MISSIONS[index - 11];
export const featureBaseScore = (index: number) => 4600 + (index - 7) * 450;
